name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Simple Test
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Package lock   
        run: npm init
      - name: Install Dependencies
        run: npm install
      - name: Run tests
        run: npm test_main
